//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CONTATOS = new HashSet<CONTATO>();
        }
    
        public int IdCliente { get; set; }
        public string NomeCliente { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<CONTATO> CONTATOS { get; set; }
    }
}
